apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: java-shopfront
spec:
  type: NodePort
  selector:
    app: catalogue
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8020
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008
