- hosts: "{{ target_host }}"
  gather_facts: false
  #become: yes
  #become_method: sudo
  #become_user: jits
  tasks:

    - name: execute mvn command for shopfront
      shell: /opt/maven/apache-maven-3.8.8/bin/mvn clean
      register: shop_output
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/shopfront"
      when: mvn == "shop" or mvn == "allapps" 

    - name: execute mvn command for productcatalogue
      command: /opt/maven/apache-maven-3.8.8/bin/mvn clean
      register: product_output
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/productcatalogue
      when: mvn == "product" or mvn == "allapps"

    - name: execute mvn command for stockmanager
      command: /opt/maven/apache-maven-3.8.8/bin/mvn clean
      register: stock_output
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/stockmanager
      when: mvn == "stock" or mvn == "allapps"