- hosts: localhost
  gather_facts: false
  #become: yes
  #become_method: sudo
  #become_user: root
  tasks:

    - name: execute mvn command for shopfront
      shell: mvn clean
      register: output
      args:
        chdir: docker-Java-kubernetes-project/shopfront
      when: mvn == "shop"

    - debug: var="output"  

    - name: execute mvn command for productcatalogue
      command: mvn clean package
      args:
        chdir: ../productcatalogue
      when: mvn == "product"

    - name: execute mvn command for stockmanager
      command: mvn clean package
      args:
        chdir: ../stockmanager
      when: mvn == "stock"