- hosts: localhost
  gather_facts: false
  become: yes
  #become_method: sudo
  become_user: root
  tasks:

    - name: execute mvn command for shopfront
      command: whoami && ls -ltr && mvn clean package
      args:
        chdir: ../shopfront
      when: mvn == "shop"

    - name: execute mvn command for productcatalogue
      command: mvn clean package
      args:
        chdir: ../productcatalogue
      when: mvn == "product"

    - name: execute mvn command for stockmanager
      command: mvn clean package
      args:
        chdir: ../stockmanager
      when: mvn == "stock"