- hosts: localhost
  gather_facts: false
  #become: yes
  #become_method: sudo
  #become_user: jits
  tasks:

    - name: execute mvn command for shopfront
      shell: pwd && whoami && /opt/maven/apache-maven-3.8.8/bin/mvn clean
      register: output
      args:
        chdir: ../shopfront
      when: mvn == "shop"

    - debug: var="output"  

    - name: execute mvn command for productcatalogue
      command: mvn clean package
      args:
        chdir: ../productcatalogue
      when: mvn == "product"

    - name: execute mvn command for stockmanager
      command: mvn clean package
      args:
        chdir: ../stockmanager
      when: mvn == "stock"