- hosts: localhost
  gather_facts: false
  #become: yes
  #become_method: sudo
  #become_user: jits
  tasks:

    - name: execute mvn command for shopfront
      shell: /opt/maven/apache-maven-3.8.8/bin/mvn clean package
      register: output
      args:
        chdir: ../shopfront
      when: mvn == "shop" or mvn == "allapps"

    - debug: var="output"  

    - name: execute mvn command for productcatalogue
      command: /opt/maven/apache-maven-3.8.8/bin/mvn clean package
      args:
        chdir: ../productcatalogue
      when: mvn == "product" or mvn == "allapps"

    - name: execute mvn command for stockmanager
      command: /opt/maven/apache-maven-3.8.8/bin/mvn clean package
      args:
        chdir: ../stockmanager
      when: mvn == "stock" or mvn == "allapps"